# Generated by Django 5.0.2 on 2024-04-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('idUsuardo', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=300)),
                ('cpf', models.CharField(max_length=11)),
                ('num_CNH', models.CharField(max_length=15, null=True)),
                ('validade_CNH', models.DateField(help_text='Forhato <em›yyyy-MM-DD</ em>', null=True)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=300, null=True)),
            ],
        ),
    ]
